kind: Service
apiVersion: v1
metadata:
  name:  neo4j
  namespace: neo4j
spec:
  selector:
    name:  neo4j
  type:  ClusterIP
  ports:
  - name:  ui-port
    port:  7474
    targetPort:  7474
  - name:  backend-port
    port:  7687
    targetPort:  7687
  externalIPs:
  - 192.168.59.109