apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4jpvc
  namespace: neo4j
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: neo4jpv
